# Generated by Django 3.2.5 on 2022-04-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_time', models.DateTimeField(verbose_name='发布时间')),
                ('content', models.CharField(max_length=50, verbose_name='弹幕内容')),
            ],
        ),
    ]
