# Generated by Django 3.2.5 on 2022-04-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='img',
            field=models.ImageField(upload_to='image', verbose_name='图片'),
        ),
    ]
