# Generated by Django 3.2.5 on 2022-04-15 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_alter_history_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='img',
            field=models.ImageField(upload_to='', verbose_name='图片'),
        ),
    ]
