# Generated by Django 4.0.4 on 2022-04-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0003_alter_new_member_email_alter_new_member_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发送时间'),
        ),
    ]
