# Generated by Django 4.0.4 on 2022-05-05 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0005_alter_emailverifyrecord_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='New_member',
            new_name='NewMember',
        ),
    ]
