# Generated by Django 4.0.4 on 2022-05-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.IntegerField(verbose_name='部门ID')),
                ('department', models.CharField(max_length=10, verbose_name='部门')),
                ('department_en', models.CharField(max_length=30, verbose_name='部门英文名称')),
                ('content', models.CharField(max_length=800, verbose_name='内容')),
                ('introduction', models.CharField(max_length=800, verbose_name='介绍')),
            ],
            options={
                'verbose_name_plural': '部门详情',
                'db_table': 'it_Department',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(verbose_name='年级')),
                ('did', models.IntegerField(verbose_name='部门ID')),
                ('department', models.CharField(max_length=10, verbose_name='部门')),
            ],
            options={
                'verbose_name_plural': '历史表',
                'db_table': 'it_History',
            },
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, upload_to='avatar', verbose_name='头像')),
                ('did', models.IntegerField(default=0, verbose_name='所属部门ID')),
                ('grade', models.IntegerField(verbose_name='年级')),
                ('name', models.CharField(max_length=10, verbose_name='成员姓名')),
                ('motto', models.CharField(max_length=30, verbose_name='座右铭')),
                ('department', models.CharField(max_length=10, verbose_name='所属部门')),
            ],
            options={
                'verbose_name_plural': '部门成员',
                'db_table': 'it_Members',
            },
        ),
    ]
