# Generated by Django 4.0.4 on 2022-04-15 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='部门名称')),
                ('picture', models.ImageField(upload_to='', verbose_name='部门图标')),
            ],
        ),
        migrations.CreateModel(
            name='EmailVerifyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='验证码')),
                ('email', models.EmailField(max_length=50, verbose_name='邮箱')),
                ('send_time', models.DateTimeField(auto_now=True, verbose_name='发送时间')),
            ],
        ),
        migrations.CreateModel(
            name='New_member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('major', models.CharField(max_length=20, verbose_name='年级专业')),
                ('phone_number', models.CharField(max_length=11, verbose_name='手机号码')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('department', models.CharField(max_length=10, verbose_name='意向部门')),
                ('expectation', models.CharField(max_length=10, verbose_name='期待的话')),
                ('schedule', models.SmallIntegerField(choices=[(0, '尚未提交'), (1, '已报名'), (2, '初审中'), (3, '面试中'), (4, '笔试中'), (5, '成功录取'), (-1, '初审失败'), (-2, '面试失败'), (-3, '笔试失败'), (-4, '复试失败'), (-5, '未录取')], verbose_name='报名状态')),
                ('verification_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='enroll.emailverifyrecord', verbose_name='邮箱验证码')),
            ],
        ),
    ]
