# Generated by Django 4.0.4 on 2022-04-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_member',
            name='schedule',
            field=models.SmallIntegerField(choices=[(0, '尚未提交'), (1, '已报名'), (2, '初审中'), (3, '面试中'), (4, '笔试中'), (5, '成功录取'), (-1, '初审失败'), (-2, '面试失败'), (-3, '笔试失败'), (-4, '复试失败'), (-5, '未录取')], default=0, verbose_name='报名状态'),
        ),
        migrations.AlterField(
            model_name='new_member',
            name='verification_code',
            field=models.CharField(max_length=4),
        ),
    ]
