# Generated by Django 4.0.4 on 2022-04-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_alter_new_member_schedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_member',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='new_member',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, verbose_name='手机号码'),
        ),
    ]
