# Generated by Django 3.2.5 on 2022-05-05 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(verbose_name='年份')),
                ('name', models.CharField(max_length=30, verbose_name='事件名称')),
                ('description', models.CharField(max_length=200, verbose_name='事件描述')),
                ('img', models.ImageField(upload_to='image', verbose_name='图片')),
            ],
        ),
    ]
