# Generated by Django 3.2.5 on 2022-05-15 00:27

from django.db import migrations, models
import utils.ImageStorage


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='img',
            field=models.ImageField(blank=True, null=True, storage=utils.ImageStorage.ImageStorage(), upload_to='image', verbose_name='图片'),
        ),
    ]
